### ISSUE TITLE
Volume for current time frame is always 0

### ISSUE THREAD

**Issue by lucasmtz** [aruancaf/stock-trading-bot#14]
Hi,

First of all, thanks for sharing this repository!

I have been trying to use it for trading a paper alpaca account, but it does not buy anything since it **returns 0 volume for the latest tick for all stocks.** The `volume_checker` function inside `stock_analysis.py` always returns 0, so,  when calling the `daytrading_stock_analyzer` from `runner.py` the IF condition is not satisfied as the `stock_score` is 0.

I have checked the module `stock_data_gather.py` and noticed that the **volume** for the latest interval from the `historical_stock_data` is 0. The other values are okay, however as the latest tick is 0 the **volume** stored in `stock_data` is also 0. This value is the one used inside the `volume_checker` later.

Sorry if I am being confusing, but I would appreciate it if someone could help me with this issue.

Thank you in advance!

**Comment by lucasmtz** [comment]
Hi,

First of all, thanks for sharing this repository!

I have been trying to use it for trading a paper alpaca account, but it does not buy anything since it **returns 0 volume for the latest tick for all stocks.** The `volume_checker` function inside `stock_analysis.py` always returns 0, so,  when calling the `daytrading_stock_analyzer` from `runner.py` the IF condition is not satisfied as the `stock_score` is 0.

I have checked the module `stock_data_gather.py` and noticed that the **volume** for the latest interval from the `historical_stock_data` is 0. The other values are okay, however as the latest tick is 0 the **volume** stored in `stock_data` is also 0. This value is the one used inside the `volume_checker` later.

Sorry if I am being confusing, but I would appreciate it if someone could help me with this issue.

Thank you in advance!

**Comment by aoberai** [comment]
Sure, will look into this today / tomorrow.

**Comment by aoberai** [comment]
Ok, so took a look at the code. When I run it, the volume is not showing up as 0. There actually is no function that is just telling you the volume, the function inside stock_data_gatherer.py is get_volume_slope which just checks the last n minutes of data and sees whether it's gone up, stayed close to the same, or gone down. Similarly, there is a get_price_slope which can give you info on whether the price has gone up, down, or stayed relatively the same. The idea with this strategy is that if both the volume and the stock price are going up together, that may be an indicator that the stock is one that should be purchased. Similarly, if the stock price is going down and the volume is high, then it is time to sell. 

Does that answer your question?

**Comment by aoberai** [comment]
Will close this issue if this is resolved
