### ISSUE TITLE
Accuracy and dev branch

### ISSUE THREAD

**Issue by fabiofdsantos** [aruancaf/stock-trading-bot#15]
Thanks for sharing this repo! I have some questions..

1) Current accuracy?

2) I noticed some TO-DOs and `nn-buy-sell-prediction` is 10 commits ahead of master. Which branch should receive PRs?

**Comment by aoberai** [comment]
Hello! What do you mean by current accuracy? Also, master is the branch currently accepting PRs if you are looking to make some

**Comment by fabiofdsantos** [comment]
Sry, by accuracy I mean.. Is the bot profitable?

**Comment by SamBanerjee007** [comment]
Thanks for sharing this - any back testing results ?

**Comment by aoberai** [comment]
I do not have backtesting setup yet. If someone wants to do that, send a pull request. I only tested the bot for a short period of time so I don't really have a trustworthy number for expected returns - was meant more to be a fun 1-week side project than anything which would personally make me any money.

**Comment by SamBanerjee007** [comment]
Thanks @aoberai amazing stuff for a quick side project -
