### ISSUE TITLE
docker help

### ISSUE THREAD

**Issue by Faisalnwz01** [aruancaf/stock-trading-bot#7]
can you add a docker file so we can run it on docker? seems like some of the deps in the requirement.txt are Linux specific.

**Comment by aoberai** [comment]
Thank you for your question! I have now updated the requirements.txt to remove the incorrect dependencies and have tested it out on windows using WSL and command prompt. The readme has the updated instructions for installing the libraries. Please let me know if that did not work, and I can create a docker file for the project.

Have a good day.

**Comment by Faisalnwz01** [comment]
Thanks, 

I had to add these few more dependencies to get it to work on mac

```
yfinance==0.1.55
nltk==3.5
newsapi-python==0.2.6
```

PS:

Had to download the Vader lexicon from nltk using the download method.

```
#add this line to news_classifier.py
nltk.download('vader_lexicon')
```

**Comment by aoberai** [comment]
I have pushed the fixes. Let me know if you have any other issues or questions. It seems that I added newsapi dependency to requirements.txt instead of newsapi-python so the sentiment analysis was not working
